version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019 Preview
configuration:
- Debug
- Release
platform: x86
build:
  project: Project\Windows\Dorothy.sln
  parallel: true
  verbosity: normal
test: off
